Document: chemkit
Title: Debian chemkit Manual
Author: <insert document author here>
Abstract: This manual describes what chemkit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chemkit/chemkit.sgml.gz

Format: postscript
Files: /usr/share/doc/chemkit/chemkit.ps.gz

Format: text
Files: /usr/share/doc/chemkit/chemkit.text.gz

Format: HTML
Index: /usr/share/doc/chemkit/html/index.html
Files: /usr/share/doc/chemkit/html/*.html
